[tool.poetry]
name = "poetry"
version = "0.1.0"
description = ""
authors = ["vitalik12345678 <vitalik142003@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
