"""empty message

Revision ID: a910e9ee5269
Revises: 
Create Date: 2021-11-05 10:25:09.772197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a910e9ee5269'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advertisement',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('protectedStatus', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('login', sa.String(length=24), nullable=False),
    sa.Column('password', sa.String(length=48), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.Column('userStatus', sa.String(length=40), nullable=False),
    sa.Column('locationId', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('login')
    )
    op.create_table('location',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('advertisement_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['advertisement_id'], ['advertisement.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('advertisement_id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('location_id')
    )
    op.create_table('message',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('advertisement_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['advertisement_id'], ['advertisement.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('advertisement_id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('text')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message')
    op.drop_table('location')
    op.drop_table('users')
    op.drop_table('advertisement')
    # ### end Alembic commands ###
